name:  App Build Test and Publish - Branch
 
#
# This workflow provides a continuous integration workflow for all branches other than the default branch.
#


on:
  push:
    branches-ignore:
      - main

jobs:
  build_parameters:
    name: Define Build Parameters

    runs-on: ubuntu-latest

    # We need to share details across job boundaries, expose the step outs at the job level
    outputs:
      maven_changelist: ${{ steps.build_params.outputs.maven_changelist }}
      maven_sha1: ${{ steps.build_params.outputs.maven_sha1 }}
      github_branch_name: ${{ steps.build_params.outputs.github_ref_branch_name }}
      github_short_sha: ${{ steps.build_params.outputs.github_short_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define Build Parameters
        id: build_params
        uses: actions/github-script@v3
        with:
          script: |
            const scriptPath = require('path').resolve('./.github/workflows/scripts/build_parameters.js')
              , buildParameters = require(scriptPath);
            ;
            buildParameters(context, core).injectBuildParameters();


  build:
    name: Build, Test, Package and Deploy snapshot app version

    needs:
      - build_parameters

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        java: [ '11' ]

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      # Utilize caching of the resolved plugins and dependencies from previous Maven builds to provide
      # faster builds when dependencies have not changed.
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # Hash on the POM file as that would need to change to modify the dependencies or plugins in use
          key: mvn-${{ matrix.java }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-${{ matrix.java }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
            mvn-${{ matrix.java }}-${{ runner.os }}
            mvn-${{ matrix.java }}
            mvn-

      - name: Build Test and Package
        id: maven_build
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_PAT }}
        run: |
          mvn package -B \
            -Dsha1="${{ needs.build_parameters.outputs.maven_sha1 }}" \
            -Dchangelist="${{ needs.build_parameters.outputs.maven_changelist }}" \
            -Dgithub.repository="${GITHUB_REPOSITORY}" 
        shell: bash
        
      - name: Deploy to GitHub Packages
        id: maven_deploy_snapshot
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_PAT }}
        run: |
          mvn deploy -B \
            -Dsha1="${{ needs.build_parameters.outputs.maven_sha1 }}" \
            -Dchangelist="${{ needs.build_parameters.outputs.maven_changelist }}" \
            -Dgithub.repository="${GITHUB_REPOSITORY}" 
        shell: bash
            
      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-buildx-action@v1
      - name: Sign in to GitHub Container Registry
        if: matrix.os == 'ubuntu-latest'
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_PAT }}
          registry: ghcr.io
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "ghcr.io/${{ steps.maven_build.outputs.container_image_name }}:${{ steps.maven_build.outputs.container_version }}"

      - name: debug
        run: |
          ls -las
      
      

      # - name: Publish Container image
      #   id: container_publish
      #   run: |
      #     docker push ${{ steps.maven_build.outputs.container_registry }}/${{ steps.maven_build.outputs.container_image }}:${{ steps.maven_build.outputs.container_version }}

      # - name: Publish App Container as a Status
      #   id: container_image_status
      #   uses: Sibz/github-status-action@v1
      #   with:
      #     authToken: ${{ secrets.GITHUB_TOKEN }}
      #     state: success
      #     context: Container Image Published - App
      #     description: ${{ steps.maven_build.outputs.container_image }}:${{ steps.maven_build.outputs.container_version }}
