name:  test
 
on:
  workflow_run:
    workflows: [ xyz ]    
    types: [ completed ]

permissions: write-all

jobs:
  test_this:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.REPOPACKAGES_PAT }}
      - name: test
        run: echo test